<?php
    echo "
        <footer>\n
            <a href=\"mailto:103936755@student.swin.edu.au\" target=\"_blank\">103936755 - Jacky Yao</a>\n
            <a href=\"mailto:103622407@student.swin.edu.au\" target=\"_blank\">103622407 - Jack Davies</a>\n
            <a href=\"mailto:103499753@student.swin.edu.au\" target=\"_blank\">103499753 - Thien An Ly</a>\n
            <a href=\"mailto:103800614@student.swin.edu.au\" target=\"_blank\">103800614 - Ravish Randev Kulathanthilage</a>\n
            <a href=\"mailto:103840759@student.swin.edu.au\" target=\"_blank\">103840759 - Jian Jia Ng</a>\n
        </footer>
    ";
?>